apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx
    env: dev
spec:
  clusterIP: None
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    targetPort: 80
